version: '3.4'

services:
    
  node:
    restart: always
    container_name: tplatt-API-Assignment
    environment:
      NODE_NUMBER: 1
    ports:
      - '30661:3000' 
    build:
      context: .
      dockerfile: ./Dockerfile.node
    depends_on:
      mongo:
        condition: service_healthy
        restart: true

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: t4J22uR8nEJYbe99zX4eQyFa5BA7VZF7A65e3zHk3gM2LUwUJF
    volumes: 
      database_volume:/data/db

volumes:
  database_volume:


    

